//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class field_scheduled
    {
        public int ID { get; set; }
        public Nullable<int> FIELD_ID { get; set; }
        public Nullable<int> FIELD_ITEM_ID { get; set; }
        public Nullable<System.DateTime> SCHEDULED_DATE { get; set; }
        public Nullable<System.TimeSpan> START_TIME { get; set; }
        public Nullable<System.TimeSpan> END_TIME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string REMARK { get; set; }
    }
}
