//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class field_item
    {
        public int ID { get; set; }
        public Nullable<int> FIELD_ID { get; set; }
        public Nullable<int> BUSINESSES_ID { get; set; }
        public Nullable<int> LEVEL { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string BRIEF { get; set; }
    }
}
