//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_scheduled
    {
        public int ID { get; set; }
        public int TEAM_A_ID { get; set; }
        public int TEAM_B_ID { get; set; }
        public System.DateTime START_TIME { get; set; }
        public System.DateTime END_TIME { get; set; }
        public Nullable<int> FIELD_ID { get; set; }
        public string GROUP_CODE { get; set; }
        public Nullable<int> FIELD_ITEM_ID { get; set; }
        public Nullable<int> FIELD_ORDER_ID { get; set; }
    }
}
