//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int ID { get; set; }
        public Nullable<int> ACCOUNT_ID { get; set; }
        public string NAME { get; set; }
        public bool IS_TEAMLEADER { get; set; }
        public string CELLPHONE { get; set; }
        public string EMAIL { get; set; }
        public string ADRESS { get; set; }
        public string AREA_CODE { get; set; }
        public string MEMBERcol { get; set; }
        public int LEVLE { get; set; }
        public Nullable<int> SCORE { get; set; }
    }
}
