//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tiqiuEntities : DbContext
    {
        public tiqiuEntities()
            : base("name=tiqiuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<account> accounts { get; set; }
        public DbSet<account_b> account_b { get; set; }
        public DbSet<account_b_businesses> account_b_businesses { get; set; }
        public DbSet<business> businesses { get; set; }
        public DbSet<dict_team_role> dict_team_role { get; set; }
        public DbSet<field> fields { get; set; }
        public DbSet<field_item> field_item { get; set; }
        public DbSet<field_order> field_order { get; set; }
        public DbSet<field_rule> field_rule { get; set; }
        public DbSet<field_scheduled> field_scheduled { get; set; }
        public DbSet<game_scheduled> game_scheduled { get; set; }
        public DbSet<member> members { get; set; }
        public DbSet<right> rights { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<role_account_b> role_account_b { get; set; }
        public DbSet<role_right> role_right { get; set; }
        public DbSet<sms_confirm> sms_confirm { get; set; }
        public DbSet<sms_history> sms_history { get; set; }
        public DbSet<sms_pool> sms_pool { get; set; }
        public DbSet<team> teams { get; set; }
        public DbSet<team_member> team_member { get; set; }
        public DbSet<team_score> team_score { get; set; }
    }
}
