//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_history
    {
        public int SMS_POOL_ID { get; set; }
        public int FIELD_ORDER_ID { get; set; }
        public Nullable<int> MEMBER_ID { get; set; }
        public Nullable<int> BUSINESSES_ID { get; set; }
        public string CELL_PHONE { get; set; }
        public string CONTENT { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
    }
}
