//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class team_score
    {
        public int ID { get; set; }
        public int FIELD_ORDER_ID { get; set; }
        public int TEAM_A_ID { get; set; }
        public int TEAM_B_ID { get; set; }
        public int TEAM_A_SCORE { get; set; }
        public string TEAM_A_NAME { get; set; }
        public string TEAM_B_NAME { get; set; }
        public System.DateTime START_TIME { get; set; }
        public System.DateTime END_TIME { get; set; }
        public string SCORE { get; set; }
        public Nullable<int> RECEIVE_SCORE { get; set; }
        public Nullable<int> LOSE_SCORE { get; set; }
    }
}
