//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIELD_SCHEDULED
    {
        public int ID { get; set; }
        public int FIELD_ID { get; set; }
        public int FIELD_ITEM_ID { get; set; }
        public System.DateTime SCHEDULED_DATE { get; set; }
        public System.TimeSpan START_TIME { get; set; }
        public System.TimeSpan END_TIME { get; set; }
        public decimal PRICE { get; set; }
        public int STATUS { get; set; }
        public string REMARK { get; set; }
        public int RULE_TYPE { get; set; }
    }
}
