//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIELD_ORDER
    {
        public FIELD_ORDER()
        {
            this.FIELD_ORDER_LOG = new HashSet<FIELD_ORDER_LOG>();
        }
    
        public int ID { get; set; }
        public int FIELD_SCHEDULED_ID { get; set; }
        public int FIELD_ID { get; set; }
        public int FIELD_ITEM_ID { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public bool NEED_REFEREE { get; set; }
        public int STATUS { get; set; }
        public System.TimeSpan START_TIME { get; set; }
        public System.TimeSpan END_TIME { get; set; }
        public int MEMBER_ID { get; set; }
        public System.DateTime EXPIRE_DATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int TYPE { get; set; }
        public Nullable<int> PK_PAY_TYPE { get; set; }
        public Nullable<decimal> INCOME { get; set; }
        public Nullable<int> SCORE { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> MEMBERB_ID { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<int> PRICE_UNIT { get; set; }
        public Nullable<int> FREE_TEAM_MIN_PLAYER { get; set; }
    
        public virtual TEAM_SCORE TEAM_SCORE { get; set; }
        public virtual ICollection<FIELD_ORDER_LOG> FIELD_ORDER_LOG { get; set; }
    }
}
