//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE
    {
        public int ID { get; set; }
        public int TYPE { get; set; }
        public int FK_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_EXT { get; set; }
        public int ORDER { get; set; }
        public Nullable<int> SIZE { get; set; }
        public Nullable<int> UPLOAD_MEMBER_ID { get; set; }
        public Nullable<System.DateTime> UPLOAD_DATE { get; set; }
        public string PATH { get; set; }
        public string TITLE { get; set; }
        public string LINK_URL { get; set; }
        public Nullable<int> OperationType { get; set; }
    }
}
