//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FREE_TEAM_LOG
    {
        public int ID { get; set; }
        public int FIELD_ORDER_ID { get; set; }
        public int MEMBER_ID { get; set; }
        public System.DateTime CHECKIN_DATE { get; set; }
        public int PLAYER_COUNT { get; set; }
        public int STATUS { get; set; }
        public Nullable<System.DateTime> CONFIRM_DATE { get; set; }
    }
}
