//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME_EVENT
    {
        public int ID { get; set; }
        public int GAME_ID { get; set; }
        public int ROUND_ID { get; set; }
        public int GROUP_ID { get; set; }
        public int SCHEDULED_ID { get; set; }
        public int TEAM_ID { get; set; }
        public int TYPE { get; set; }
        public int PLAYER_NUMBER { get; set; }
        public System.TimeSpan TIMESPAN { get; set; }
        public int RECORD_ID { get; set; }
        public System.DateTime RECORD_DATE { get; set; }
        public string MEMBER_NAME { get; set; }
        public Nullable<int> MEMBER_ID { get; set; }
    
        public virtual GAME_SCHEDULED GAME_SCHEDULED { get; set; }
    }
}
