//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME_SCHEDULED
    {
        public GAME_SCHEDULED()
        {
            this.GAME_EVENT = new HashSet<GAME_EVENT>();
        }
    
        public int ID { get; set; }
        public int GAME_ID { get; set; }
        public int ROUND_ID { get; set; }
        public int GROUP_ID { get; set; }
        public int TEAM_A_ID { get; set; }
        public int TEAM_B_ID { get; set; }
        public System.DateTime GAME_DATE { get; set; }
        public System.TimeSpan START_TIME { get; set; }
        public System.TimeSpan END_TIME { get; set; }
        public Nullable<int> FIELD_ID { get; set; }
        public Nullable<int> FIELD_ITEM_ID { get; set; }
        public Nullable<int> FIELD_ORDER_ID { get; set; }
        public Nullable<int> TEAM_A_GOAL { get; set; }
        public Nullable<int> TEAM_B_GOAL { get; set; }
        public Nullable<int> TEAM_A_SCORE { get; set; }
        public Nullable<int> TEAM_B_SCORE { get; set; }
        public string TEAM_A_NAME { get; set; }
        public string TEAM_B_NAME { get; set; }
        public string FIELD_ITEM_FULL_NAME { get; set; }
        public int STATUS { get; set; }
    
        public virtual GAME_ROUND_GROUP GAME_ROUND_GROUP { get; set; }
        public virtual ICollection<GAME_EVENT> GAME_EVENT { get; set; }
    }
}
