//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME_ROUND_GROUP
    {
        public GAME_ROUND_GROUP()
        {
            this.GAME_SCHEDULED = new HashSet<GAME_SCHEDULED>();
            this.GAME_TEAM = new HashSet<GAME_TEAM>();
        }
    
        public int ID { get; set; }
        public int GAME_ID { get; set; }
        public int ROUND_ID { get; set; }
        public string NAME { get; set; }
        public int SORT { get; set; }
    
        public virtual ICollection<GAME_SCHEDULED> GAME_SCHEDULED { get; set; }
        public virtual GAME_ROUND GAME_ROUND { get; set; }
        public virtual ICollection<GAME_TEAM> GAME_TEAM { get; set; }
    }
}
