//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME_ROUND
    {
        public GAME_ROUND()
        {
            this.GAME_ROUND_GROUP = new HashSet<GAME_ROUND_GROUP>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public System.DateTime START_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public int STATUS { get; set; }
        public int ROUND_TYPE { get; set; }
        public string BRIEF { get; set; }
        public int GAME_ID { get; set; }
    
        public virtual GAME GAME { get; set; }
        public virtual ICollection<GAME_ROUND_GROUP> GAME_ROUND_GROUP { get; set; }
    }
}
