//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushMessages
    {
        public int SysNo { get; set; }
        public string UserID { get; set; }
        public string PushType { get; set; }
        public string Tag { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public string Message { get; set; }
        public Nullable<int> Status { get; set; }
        public string RequestID { get; set; }
        public int RetryCount { get; set; }
        public string ChannelID { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
        public int MessageType { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<int> PkId { get; set; }
        public Nullable<System.DateTime> PlanSendDate { get; set; }
    }
}
