//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS
    {
        public int ID { get; set; }
        public string PHONE { get; set; }
        public string MESSAGE { get; set; }
        public System.DateTime CTEATE_TIME { get; set; }
        public System.DateTime PLAN_SEND_TIME { get; set; }
        public int PRIORITY { get; set; }
        public int STATUS { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
        public Nullable<System.DateTime> SEND_TIME { get; set; }
        public string EXT_INFO { get; set; }
        public Nullable<int> SMS_SEQID { get; set; }
        public string SMS_NUMBER { get; set; }
        public string ERROR_CODE { get; set; }
        public Nullable<int> MEMBER_ID { get; set; }
        public Nullable<int> ACCOUNT_B_ID { get; set; }
        public int RETRY_COUNT { get; set; }
    }
}
