//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TIQIUEntities : DbContext
    {
        public TIQIUEntities()
            : base("name=TIQIUEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public DbSet<AREA> AREAs { get; set; }
        public DbSet<DICT_TEAM_ROLE> DICT_TEAM_ROLE { get; set; }
        public DbSet<FIELD> FIELDs { get; set; }
        public DbSet<FIELD_ITEM> FIELD_ITEM { get; set; }
        public DbSet<FIELD_ORDER> FIELD_ORDER { get; set; }
        public DbSet<FIELD_RULE> FIELD_RULE { get; set; }
        public DbSet<FIELD_SCHEDULED> FIELD_SCHEDULED { get; set; }
        public DbSet<FILE> FILEs { get; set; }
        public DbSet<FREE_TEAM_LOG> FREE_TEAM_LOG { get; set; }
        public DbSet<RIGHT> RIGHTs { get; set; }
        public DbSet<ROLE> ROLEs { get; set; }
        public DbSet<ROLE_ACCOUNT_B> ROLE_ACCOUNT_B { get; set; }
        public DbSet<ROLE_RIGHT> ROLE_RIGHT { get; set; }
        public DbSet<TEAM> TEAMs { get; set; }
        public DbSet<TEAM_MEMBER> TEAM_MEMBER { get; set; }
        public DbSet<TEAM_SCORE> TEAM_SCORE { get; set; }
        public DbSet<V_FIELD_ITEM_SCHEDULED> V_FIELD_ITEM_SCHEDULED { get; set; }
        public DbSet<V_FIELD_ORDER> V_FIELD_ORDER { get; set; }
        public DbSet<V_FIELD_SCHEDULED> V_FIELD_SCHEDULED { get; set; }
        public DbSet<ACCOUNT_B_BUSINESSES> ACCOUNT_B_BUSINESSES { get; set; }
        public DbSet<ACCOUNT_B> ACCOUNT_B { get; set; }
        public DbSet<BUSINESSES> BUSINESSES { get; set; }
        public DbSet<VIEW_ORDER_FREETEAM> VIEW_ORDER_FREETEAM { get; set; }
        public DbSet<VIEW_ORDER_PK> VIEW_ORDER_PK { get; set; }
        public DbSet<MEMBER> MEMBER { get; set; }
        public DbSet<FIELD_ORDER_BATCH> FIELD_ORDER_BATCH { get; set; }
        public DbSet<SMS_RECEIVE> SMS_RECEIVE { get; set; }
        public DbSet<SMS> SMS { get; set; }
        public DbSet<GAME> GAME { get; set; }
        public DbSet<GAME_EVENT> GAME_EVENT { get; set; }
        public DbSet<GAME_ROUND> GAME_ROUND { get; set; }
        public DbSet<GAME_ROUND_GROUP> GAME_ROUND_GROUP { get; set; }
        public DbSet<GAME_TEAM> GAME_TEAM { get; set; }
        public DbSet<GAME_SCHEDULED> GAME_SCHEDULED { get; set; }
        public DbSet<GAME_COMMENT> GAME_COMMENT { get; set; }
        public DbSet<PushMessages> PushMessages { get; set; }
        public DbSet<BAIDU_USER_MEMBER> BAIDU_USER_MEMBER { get; set; }
        public DbSet<FIELD_ORDER_LOG> FIELD_ORDER_LOG { get; set; }
        public DbSet<FEEDBACK> FEEDBACK { get; set; }
        public DbSet<VERSION> VERSION { get; set; }
        public DbSet<VIEW_GAME_MEMBER_GOAL> VIEW_GAME_MEMBER_GOAL { get; set; }
    }
}
