//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAM_MEMBER
    {
        public int ID { get; set; }
        public int MEMBER_ID { get; set; }
        public int TEAM_ID { get; set; }
        public int ROLE_ID { get; set; }
        public int STATUS { get; set; }
        public Nullable<int> TEAM_NUMBER { get; set; }
        public string POSITION { get; set; }
    
        public virtual DICT_TEAM_ROLE DICT_TEAM_ROLE { get; set; }
        public virtual TEAM TEAM { get; set; }
        public virtual MEMBER MEMBER { get; set; }
    }
}
