//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAM
    {
        public TEAM()
        {
            this.TEAM_MEMBER = new HashSet<TEAM_MEMBER>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public int LEVEL { get; set; }
        public int SCORE { get; set; }
        public int WIN { get; set; }
        public int LOSE { get; set; }
        public int DRAW { get; set; }
        public string BRIEF { get; set; }
        public System.DateTime BUILD_DATE { get; set; }
        public string DECLARATION { get; set; }
        public string FEATURE { get; set; }
        public int TYPE { get; set; }
        public int STATUS { get; set; }
    
        public virtual ICollection<TEAM_MEMBER> TEAM_MEMBER { get; set; }
    }
}
