//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FIELD_ITEM_SCHEDULED
    {
        public int ID { get; set; }
        public int BUSINESSES_ID { get; set; }
        public string AREA_CODE { get; set; }
        public Nullable<double> L { get; set; }
        public Nullable<double> B { get; set; }
        public string NAME { get; set; }
        public string BRIEF { get; set; }
        public Nullable<int> LEVEL { get; set; }
        public string ADRESS { get; set; }
        public int SCORE { get; set; }
        public bool HAS_BATHROOM { get; set; }
        public decimal BOTTOM_PRICE { get; set; }
        public decimal TOP_PRICE { get; set; }
        public int STATUS { get; set; }
        public string TEL { get; set; }
        public string PHONE { get; set; }
        public string PIC_PATH { get; set; }
        public int FIELD_ITEM_ID { get; set; }
        public int FIELD_ITEM_STATUS { get; set; }
        public string FIELD_ITEM_NAME { get; set; }
        public int TYPE { get; set; }
        public Nullable<int> SCHEDULED_ID { get; set; }
        public Nullable<System.DateTime> SCHEDULED_DATE { get; set; }
        public Nullable<System.TimeSpan> START_TIME { get; set; }
        public Nullable<System.TimeSpan> END_TIME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<int> SCHEDULED_STATUS { get; set; }
    }
}
