//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_ORDER_FREETEAM
    {
        public int ORDER_ID { get; set; }
        public int FIELD_SCHEDULED_ID { get; set; }
        public int FIELD_ID { get; set; }
        public int FIELD_ITEM_ID { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public bool NEED_REFEREE { get; set; }
        public int STATUS { get; set; }
        public System.TimeSpan START_TIME { get; set; }
        public System.TimeSpan END_TIME { get; set; }
        public System.DateTime EXPIRE_DATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int TYPE { get; set; }
        public Nullable<int> PK_PAY_TYPE { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<int> PRICE_UNIT { get; set; }
        public Nullable<int> FREE_TEAM_MIN_PLAYER { get; set; }
        public Nullable<int> PLAYER_COUNT { get; set; }
        public string FIELD_NAME { get; set; }
        public string FIELD_ITEM_NAME { get; set; }
        public int FIELD_ITEM_TYPE { get; set; }
        public string AREA_CODE { get; set; }
    }
}
