//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiQiu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_ORDER_PK
    {
        public int ORDER_ID { get; set; }
        public int FIELD_SCHEDULED_ID { get; set; }
        public int FIELD_ID { get; set; }
        public int FIELD_ITEM_ID { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public bool NEED_REFEREE { get; set; }
        public int STATUS { get; set; }
        public System.TimeSpan START_TIME { get; set; }
        public System.TimeSpan END_TIME { get; set; }
        public int MEMBER_ID { get; set; }
        public System.DateTime EXPIRE_DATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int TYPE { get; set; }
        public Nullable<decimal> INCOME { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> MEMBERB_ID { get; set; }
        public int FIELD_ORDER_ID { get; set; }
        public int TEAM_A_ID { get; set; }
        public Nullable<int> TEAM_B_ID { get; set; }
        public int TEAM_A_SCORE { get; set; }
        public string TEAM_A_NAME { get; set; }
        public string TEAM_B_NAME { get; set; }
        public string SCORE { get; set; }
        public Nullable<int> RECEIVE_SCORE { get; set; }
        public Nullable<int> LOSE_SCORE { get; set; }
        public string TEAM_A_COLOR { get; set; }
        public string TEAM_B_COLOR { get; set; }
        public string FIELD_NAME { get; set; }
        public string FIELD_ITEM_NAME { get; set; }
        public int FIELD_ITEM_TYPE { get; set; }
        public Nullable<int> PK_PAY_TYPE { get; set; }
        public string AREA_CODE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    }
}
